export const CREATE_USER_WITH_EMAIL_AND_PASSWORD_START = 'CREATE_USER_WITH_EMAIL_AND_PASSWORD_START'
export const CREATE_USER_WITH_EMAIL_AND_PASSWORD_SUCCESS = 'CREATE_USER_WITH_EMAIL_AND_PASSWORD_SUCCESS'
export const CREATE_USER_WITH_EMAIL_AND_PASSWORD_FAIL = 'CREATE_USER_WITH_EMAIL_AND_PASSWORD_FAIL'

export const SEND_PASSWORD_RESET_EMAIL_START = 'SEND_PASSWORD_RESET_EMAIL_START'
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = 'SEND_PASSWORD_RESET_EMAIL_SUCCESS'
export const SEND_PASSWORD_RESET_EMAIL_FAIL = 'SEND_PASSWORD_RESET_EMAIL_FAIL'

export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_START = 'SIGN_IN_WITH_EMAIL_AND_PASSWORD_START'
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS = 'SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS'
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAIL = 'SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAIL'

export const SIGN_IN_WITH_POPUP_START = 'SIGN_IN_WITH_POPUP_START'
export const SIGN_IN_WITH_POPUP_SUCCESS = 'SIGN_IN_WITH_POPUP_SUCCESS'
export const SIGN_IN_WITH_POPUP_FAIL = 'SIGN_IN_WITH_POPUP_FAIL'

export const SIGN_IN_ANONYMOUSLY_START = 'SIGN_IN_ANONYMOUSLY_START'
export const SIGN_IN_ANONYMOUSLY_SUCCESS = 'SIGN_IN_ANONYMOUSLY_SUCCESS'
export const SIGN_IN_ANONYMOUSLY_FAIL = 'SIGN_IN_ANONYMOUSLY_FAIL'

export const SIGN_OUT_START = 'SIGN_OUT_START'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL'
